name: Documentation Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Installing dependencies
      run: |
        npm install -g markdownlint-cli2
        npm install -g cspell
    - name: Lint
      run: markdownlint-cli2-config ".linter/.markdownlint.yaml" "*.md"
    - name: Spellcheck
      run: cspell -c .linter/cspell.json  "*.md" --show-suggestions
 